#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

genus_lists:
  path: /genus
  defaults: {_controller: AppBundle:Genus:list }

genus_new:
  path: /genus/new
  defaults: { _controller: AppBundle:Genus:new }

genus_show:
  path: /genus/{genusName}
  defaults: { _controller: AppBundle:Genus:show }

genus_show_notes:
  path: /genus/{name}/notes
  defaults: { _controller: AppBundle:Genus:getNotes }

admin_genus_list:
  path: /admin/genus
  defaults: { _controller: AppBundle:Admin\GenusAdmin:index }

admin_genus_new:
  path: /admin/genus/new
  defaults: { _controller: AppBundle:Admin\GenusAdmin:new }

admin_genus_edit:
  path: /admin/genus/{id}/edit
  defaults: { _controller: AppBundle:Admin\GenusAdmin:edit }

security_login:
  path: /login
  defaults: { _controller: AppBundle:Security:login }

security_logout:
  path: /logout
  defaults: { _controller: AppBundle:Security:logout }

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }